name: pfrp
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2021.4.13=h06a4308_1
  - certifi=2020.12.5=py37h06a4308_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_1
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.0.1=py37h06a4308_0
  - python=3.7.10=hdb3f193_0
  - readline=8.1=h27cfd23_0
  - setuptools=52.0.0=py37h06a4308_0
  - sqlite=3.35.4=hdfb4753_0
  - tk=8.6.10=hbc83047_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - absl-py==0.12.0
    - cachetools==4.2.2
    - chardet==4.0.0
    - cloudpickle==1.6.0
    - cycler==0.10.0
    - google-auth==1.30.1
    - google-auth-oauthlib==0.4.4
    - grpcio==1.38.0
    - gym==0.18.3
    - idna==2.10
    - importlib-metadata==4.2.0
    - kiwisolver==1.3.1
    - markdown==3.3.4
    - matplotlib==3.4.1
    - numpy==1.20.2
    - oauthlib==3.1.0
    - pandas==1.2.4
    - pillow==8.2.0
    - protobuf==3.17.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyglet==1.5.15
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - pytz==2021.1
    - pyzmq==22.0.3
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rl4net==0.2.6
    - rsa==4.7.2
    - scipy==1.6.3
    - six==1.15.0
    - tensorboard==2.5.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - torch==1.8.1
    - typing-extensions==3.10.0.0
    - urllib3==1.26.5
    - werkzeug==2.0.1
    - zipp==3.4.1
    - zmq==0.0.0
prefix: /root/anaconda3/envs/pfrp

